version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  flake8: &flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - setup.cfg

  pug-lint: &pug-lint
    lint-command: 'pug-lint -r inline'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c %m'

languages:
  python:
    - <<: *flake8

  pug:
    - <<: *pug-lint
