version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  node_module-eslint: &node_module-eslint
    lint-command: '.\node_modules\.bin\eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %trror %m"

  eslint: &eslint
    lint-command: 'eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %trror %m"

  pug-lint: &pug-lint
    lint-command: 'pug-lint -r inline'
    lint-stdin: false
    lint-formats:
      - "%f:%l:%c %m"

languages:
  javascript:
    - <<: *node_module-eslint
    - <<: *eslint

  typescript:
    - <<: *node_module-eslint
    - <<: *eslint

  vue:
    - <<: *node_module-eslint
    - <<: *eslint
  
  pug:
    - <<: *pug-lint
