version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  node_modules-eslint: &node_modules-eslint
    lint-command: '.\node_modules\.bin\eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%t%.%+/%r]'
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

  eslint: &eslint
    lint-command: 'eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%t%.%+/%r]'
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

  pug-lint: &pug-lint
    lint-command: 'pug-lint -r inline'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c %m'

languages:
  javascript:
    - <<: *node_modules-eslint
    - <<: *eslint

  typescript:
    - <<: *node_modules-eslint
    - <<: *eslint

  vue:
    - <<: *node_modules-eslint
    - <<: *eslint
  
  pug:
    - <<: *pug-lint
