"Options (:options)
"4 displaying text 
set columns=120
set lines=30
"10 GUI
set guioptions-=egmrLtT
set guioptions+=!

let s:gvimrc_machine_local_path = CFRCGetLocalVimFilesDir() . '/gvimrc_local'
if filereadable(s:gvimrc_machine_local_path)
    execute 'source ' . s:gvimrc_machine_local_path
endif
