"Options (:options)
"4 displaying text 
set columns=120
set lines=30
"10 GUI
set guioptions-=e
set guioptions-=g
set guioptions-=m
set guioptions-=r
set guioptions-=L
set guioptions-=t
set guioptions-=T
set guioptions+=!

"Options (:options)
"10 GUI
"set guifont=[fontname]:h[fontsize] - Windows vimrc_local
"set guifont=[fontname]\ [fontsize] - Linux vimrc_local

let s:gvimrc_machine_local_path = CFRCGetLocalVimFilesDir() . '/gvimrc_local'
if filereadable(s:gvimrc_machine_local_path)
    execute 'source ' . s:gvimrc_machine_local_path
endif
